#include $(OMEGA_HOME)/Config/GNUmakefile.config
#include $(OMEGA_HOME)/Config/GNUmakefile.rules

ifndef DYN_DOCS
 DYN_DOCS=$(HOME)/Classes/StatComputing/XDynDocs/inst
endif

include $(DYN_DOCS)/Make/Makefile
